### PR TITLE
Make message senders nick double clickable

### LINKED ISSUE #1321: quoting a user name by double-clicking
When I double click on user name on their "join" action, their nick is copied into message line.

But that feature is not working when that user sends a message (it works only on room "join" action lines). Single click shows that user info, but double-click would be more helpful for easier and quicker quote-reply.

### PR DESCRIPTION
**Pull request by ItsOnlyBinary**
This makes sender nicks linked with click and double click support and improves double click nick insert to have matching case to the users nick

also fixes click on realname in modern layout (missing `prop.`)

closes #1321

### CODE REVIEW

File: src/components/MessageListMessageModern.vue [hunk 1]
```diff
@@ -161,9 +161,9 @@ const methods = {
         }
 
         // No point showing the realname if it's the same as the nick
-        if (props.message.user.nick.toLowerCase() === props.message.user.realname.toLowerCase()) {
-            return false;
-        }
+        // if (props.message.user.nick.toLowerCase() === props.message.user.realname.toLowerCase()) {
```
Comment (prawnsalad) [inline src/components/MessageListMessageModern.vue:164]: Commented lines left over from debugging I'm guessing?

File: src/components/MessageList.vue [hunk 2]
```diff
@@ -374,9 +374,15 @@ export default {
...
-            if (userNick) {
-                this.$state.$emit('input.insertnick', userNick);
+            let dataNick = event.target.getAttribute('data-nick');
+            if (!dataNick) {
+                return;
+            }
+
+            let network = this.buffer.getNetwork();
+            let user = network.userByName(dataNick);
+            if (user && user.nick) {
```
Comment (prawnsalad) [inline src/components/MessageList.vue:384]: This will block it from inserting the nick if the user has already left the channel. It should use `dataNick` if the user object doesn't exist

**Comment by CoryChaplin** [comment]
Tested this and it works as it should 👍
