### PR TITLE
Fix sidebar width when pinned in config

### LINKED ISSUE #564: Nicklist width
After latest commits nicklist width is too wide, it back to normal size clicking on nicklist button in top right menu.

userwidth

### PR DESCRIPTION
**Pull request by ItsOnlyBinary**
fixes #564

### CODE REVIEW

File: src/components/App.vue [hunk 1]
```diff
@@ -123,10 +123,6 @@ export default {
         window.addEventListener('focus', event => this.onFocus(event), false);
         window.addEventListener('blur', event => this.onBlur(event), false);
         window.addEventListener('touchstart', event => this.onTouchStart(event));
-
-        if (this.sidebarState.canPin && this.$state.setting('sidebarPinned')) {
```
Comment (digitalcircuit) [inline src/components/App.vue]: Is removing the ability to pin the sidebar from user settings/`config.json` intentional?

After a while of looking, I can't find anywhere else that [`sidebarPinned`](https://github.com/kiwiirc/kiwiirc/wiki/Configuration-Options#sidebarpinned ) is checked.  Pardon if I'm misunderstanding; this is my first time looking through.
