### PR TITLE
Fix nick & pass not updating after failed connection attempt using Welcome.vue

### LINKED ISSUE #559: attempt to enter a new nickname during a reject
hi,

It's impossible to enter a new nickname when a server rejects you a first time

http://imgur.com/43X6BEZl.png

### PR DESCRIPTION
**Pull request by ItsOnlyBinary**
fixes #559

### CODE REVIEW

File: src/components/startups/Welcome.vue [hunk 1]
```diff
@@ -185,39 +185,34 @@ export default {
...
+                port: options.port,
+                tls: options.tls,
+                password: this.password,
+                encoding: _.trim(options.encoding),
+                direct: !!options.direct,
+                path: options.direct_path || '',
+                gecos: options.gecos,
+            });
+
+            if (!this.network && options.recaptchaSiteId) {
```
Comment (ItsOnlyBinary) [inline src/components/startups/Welcome.vue]: I added !this.network so it would only ask the first time as that's what it was originally doing, not sure if this is correct due to not having recaptcha setup.

Does recaptcha time out? would a second connection attempt work with the first recaptacha answer?
